# Starter pipeline
- task: Prisma Cloud IaC Scan@3
  inputs:
    Path: '/TF'
    prismaCloudService: 'Prisma-IaC'
    High: '1'
    Medium: '1'
    Low: '1'
    Operator: 'or'
    Tags: 'repo: iac-scan-pj'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
