# This is the configuration file for Iac Scan APIv2.

# Specify the template types.The valid values are TF, CFT, K8S
template_type: CFT

# Define tags to identify your particular scan. You can use these tags to search the scan details on the Prisma Cloud.
tags:
  Org: Engineering
  Team: Shift_Left
  Env: Dev
	
